version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    networks:
      - inception
    volumes:
    - mariadb:/var/lib/mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    expose:
      - "3306"


  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    networks:
      - inception
    volumes:
     - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: always


  wordpress:
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/manujime/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/manujime/data/mariadb'


networks:
  inception:
    driver: bridge
